name: Order Service CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B clean verify

      - name: Run Tests
        run: mvn test

      - name: Build Docker image
        run: |
          docker build -t order-service:${{ github.sha }} .
          docker tag order-service:${{ github.sha }} order-service:latest

  deploy-dev:
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Deploy to Dev
        run: |
          helm upgrade --install order-service ./helm/order-service \
          -f ./helm/order-service/environments/dev-values.yaml \
          --namespace development \
          --create-namespace \
          --wait