replicaCount: 3
resources:
  limits:
    cpu: 2000m
    memory: 2Gi
  requests:
    cpu: 1000m
    memory: 1Gi

ingress:
  hosts:
    - host: orders.production.com
      paths:
        - path: /
          pathType: Prefix

env:
  SPRING_PROFILES_ACTIVE: prod