replicaCount: 3

image:
  repository: gcr.io/gke-demo/order-service
  tag: stable

resources:
  limits:
    cpu: 2000m
    memory: 2Gi
  requests:
    cpu: 1000m
    memory: 1Gi

ingress:
  hosts:
    - host: orders.gke-demo.com

env:
  SPRING_PROFILES_ACTIVE: prod
  GOOGLE_CLOUD_PROJECT: gke-demo

gcp:
  projectId: gke-demo
  region: us-central1
  zone: us-central1-c