replicaCount: 2

image:
  repository: order-service
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: order-service.local
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

env:
  SPRING_PROFILES_ACTIVE: prod
  SERVER_PORT: 8080

configMap:
  enabled: true
  data:
    application.yml: |-
      spring:
        datasource:
          url: jdbc:h2:mem:orderdb