replicaCount: 2

image:
  repository: gcr.io/gke-demo/order-service
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: gce
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: "order-service-ip"
  hosts:
    - host: order-service.gke-demo.com
      paths:
        - path: /*
          pathType: ImplementationSpecific

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

env:
  SPRING_PROFILES_ACTIVE: prod
  SERVER_PORT: 8080
  GOOGLE_CLOUD_PROJECT: gke-demo

gcp:
  projectId: gke-demo
  region: us-central1
  zone: us-central1-c
  serviceAccountSecret: order-service-sa-key

configMap:
  enabled: true
  data:
    application.yml: |-
      spring:
        datasource:
          url: jdbc:h2:mem:orderdb