name: Order Service CI-CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B clean verify
        
    - name: Configure GCloud Credentials
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: gke-demo
        
    - name: Configure Docker for GCP
      run: gcloud auth configure-docker
        
    - name: Build and Push Docker image
      run: |
        docker build -t gcr.io/gke-demo/order-service:${{ github.sha }} .
        docker push gcr.io/gke-demo/order-service:${{ github.sha }}

  deploy-prod:
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure GCloud Credentials
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: gke-demo
    
    - name: Get GKE Credentials
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: your-cluster-name
        location: us-central1-c
    
    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: 'latest'
        
    - name: Deploy to Production
      run: |
        helm upgrade --install order-service ./helm/order-service \
        --set image.tag=${{ github.sha }} \
        -f ./helm/prod-values.yaml \
        --namespace production \
        --create-namespace \
        --wait